package mx.edu.utez.server.shared.exception;

public enum ErrorCode {
    SESSION_EXPIRED,
    INVALID_TOKEN,
    UNAUTHORIZED,
    FORBIDDEN,
    RESOURCE_NOT_FOUND,
    VALIDATION_ERROR,
    BUSINESS_RULE_VIOLATION,
    SERVICE_UNAVAILABLE,
    PROVIDER_ERROR,
    INTERNAL_ERROR
}
