spring.config.import=optional:file:.env[.properties]
spring.application.name=${APP_NAME}
spring.profiles.active=${APP_ENV}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.format_sql=false

spring.jackson.time-zone=UTC

server.port=${SERVER_PORT}

management.endpoints.web.exposure.include=health,info

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

app.jwt.secret=${APP_JWT_SECRET}
app.jwt.issuer=${APP_JWT_ISSUER:sgb-utez}
app.jwt.admin-expiration-seconds=${APP_JWT_ADMIN_EXP_SECONDS}
app.jwt.student-expiration-seconds=${APP_JWT_STUDENT_EXP_SECONDS}

app.security.allowed-origins=${APP_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:18080}
app.frontend.base-url=${APP_FRONTEND_BASE_URL:http://localhost:5173}

app.elibro.base-url=${APP_ELIBRO_BASE_URL:https://auth.elibro.net/auth/sso/}
app.elibro.encryption-key=${APP_AES_SECRET}
app.elibro.allowed-next-hosts=${APP_ELIBRO_ALLOWED_HOSTS}

app.google.allowed-domain=${APP_GOOGLE_ALLOWED_DOMAIN}
app.google.audience[0]=${APP_GOOGLE_CLIENT_ID}

app.seed.admin-email=${APP_SEED_ADMIN_EMAIL:}
app.seed.admin-password=${APP_SEED_ADMIN_PASSWORD:}
app.seed.admin-full-name=${APP_SEED_ADMIN_FULL_NAME:Administrador TI}

app.seed.admin-biblioteca-email=${APP_SEED_ADMIN_BIBLIOTECA_EMAIL:}
app.seed.admin-biblioteca-password=${APP_SEED_ADMIN_BIBLIOTECA_PASSWORD:}
app.seed.admin-biblioteca-full-name=${APP_SEED_ADMIN_BIBLIOTECA_FULL_NAME:Administrador Biblioteca}

logging.level.org.springframework.security=INFO
