package mx.edu.utez.server.modules.dashboard.dto;

public enum DashboardWidgetType {
    KPI_GROUP,
    AREA_TREND,
    TOP_STUDENTS_TABLE,
    TOP_CAREERS_TABLE,
    STUDENT_ACCESS_SUMMARY,
    STUDENT_ACTIVITY_TABLE,
    STUDENT_RANKING_TABLE,
    STUDENT_RESULT_BREAKDOWN,
    CAREER_RANKING_TABLE,
    CAREER_COMPARISON_TABLE,
    CAREER_RANKING_SUCCESS_TABLE,
    CAREER_RANKING_FAILED_TABLE,
    CAREER_RESULT_BREAKDOWN,
    CAREER_STUDENT_TABLE
}
